# Generated by Django 3.0.7 on 2020-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название приемущества курса', max_length=140, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Годное описание приемущества курса', verbose_name='Описание приемущества курса')),
                ('is_active', models.BooleanField(help_text='Есть ли набор на курс?', verbose_name='Активность приемущества курса')),
                ('image', models.ImageField(upload_to='advantage_image/', verbose_name='Иллюстрация')),
            ],
            options={
                'verbose_name': 'Приемущество',
                'verbose_name_plural': 'Приемущества',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Годное описание курса', verbose_name='Описание курса'),
        ),
    ]
