# Generated by Django 3.0.7 on 2020-09-15 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200909_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140, null=True, verbose_name='Тема урока'), blank=True, default=list, null=True, size=None, verbose_name='Список уроков'),
        ),
    ]
