# Generated by Django 3.0.7 on 2020-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Лучше если заголовок будет (поисковая оптимизация)', max_length=60, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Введите текст отзыва', verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда добавлен отзыв', verbose_name='Дата создания')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=40, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли увидеть отзыв', verbose_name='Активность отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
