# Generated by Django 3.0.7 on 2020-09-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Лучше если заголовок будет (поисковая оптимизация)', max_length=60, verbose_name='Заголовок объявления')),
                ('text', models.TextField(help_text='Введите текст объявления', verbose_name='Текст объявления')),
                ('image', models.ImageField(default='default/default_tutor_image.png', help_text='Пристойная иллюстрация', upload_to='announcement_image/', verbose_name='Иллюстрация объявления')),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли увидеть объявление', verbose_name='Активность объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
