# Generated by Django 3.0.7 on 2020-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя преподавателя', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='Фамилия преподавателя', max_length=20)),
                ('biography', models.TextField(blank=True)),
                ('image', models.ImageField(default='default/default_tutor_image.png', upload_to='tutor_image/')),
                ('is_active', models.BooleanField(help_text='Активна ли запись')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
