# Generated by Django 3.0.7 on 2020-09-15 13:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя.', max_length=40, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите телефонный номер', max_length=128, region=None, verbose_name='Телефонный номер')),
                ('email', models.EmailField(help_text='Введите телефонный номер', max_length=254, verbose_name='Электронная почта')),
                ('subject', models.CharField(help_text='Кратко опишите суть', max_length=60, verbose_name='Тема сообщения')),
                ('message', models.TextField(blank=True, help_text='Развёрнуто опишите вопрос', verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Холодный контакт',
                'verbose_name_plural': 'Холодные контакты',
            },
        ),
    ]
