# Generated by Django 3.0.7 on 2020-09-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200923_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('0', 'новое'), ('1', 'в процессе'), ('2', 'завершено')], default='новое', max_length=10, verbose_name='Статус')),
                ('is_done', models.BooleanField(default=False, verbose_name='Завершено')),
                ('notice', models.TextField(verbose_name='Текст сообщения')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leads.Lead')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
