# Generated by Django 3.0.7 on 2020-09-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('0', 'новое'), ('1', 'в процессе'), ('2', 'завершено')], default='новое', max_length=1, verbose_name='Статус'),
        ),
    ]
