# Generated by Django 3.0.7 on 2020-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Лучше если название будет (поисковая оптимизация)', max_length=20, verbose_name='Название иллюстрации')),
                ('image', models.ImageField(blank=True, upload_to='project_image/', verbose_name='Иллюстрация')),
            ],
            options={
                'verbose_name': 'Иллюстрация',
                'verbose_name_plural': 'Иллюстрации',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название проекта', max_length=140, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Годное описание проекта', verbose_name='Описание проекта')),
                ('is_active', models.BooleanField(help_text='Есть ли набор на курс?', verbose_name='Активность проекта')),
                ('images', models.ManyToManyField(help_text='Пусть лучше будут картинки', to='projects.ProjectImage', verbose_name='Иллюстрации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
